AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

# https://github.com/lovewithfood/rubocop-rspec-focused
require:
  - rubocop/rspec/focused

RSpec/Focused:
  Enabled: true
